# Generated by Django 3.0.5 on 2020-04-10 03:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(default='', max_length=256, verbose_name='銀行名')),
                ('branch', models.CharField(default='', max_length=256, verbose_name='支店名')),
                ('account_name', models.CharField(default='', max_length=256, verbose_name='口座人名義')),
                ('account_num', models.CharField(default='', max_length=256, verbose_name='口座番号')),
                ('account_type', models.CharField(default='', max_length=256, verbose_name='口座種別')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '口座情報',
                'db_table': 'restaurant_bank_account',
            },
        ),
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('municipalities_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256, verbose_name='市区町村')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '市区町村',
                'db_table': 'restaurant_municipalities',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('prefecture_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256, verbose_name='都道府県')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '都道府県',
                'db_table': 'restaurant_prefecture',
            },
        ),
        migrations.CreateModel(
            name='StreetName',
            fields=[
                ('municipalities_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256, verbose_name='町名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '町名',
                'db_table': 'restaurant_street_name',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip_code', models.CharField(default='', max_length=256, verbose_name='郵便番号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipalities', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Municipalities', verbose_name='市区町村')),
                ('prefecture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Prefecture', verbose_name='都道府県')),
                ('street_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.StreetName', verbose_name='町名')),
            ],
            options={
                'verbose_name_plural': '郵便番号',
                'db_table': 'restaurant_zip_code',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='レストラン名')),
                ('owner', models.CharField(default='', max_length=256, verbose_name='オーナ名')),
                ('street_num', models.CharField(default='', max_length=256, verbose_name='番地')),
                ('bldg', models.CharField(default='', max_length=256, verbose_name='建物名')),
                ('web_url', models.URLField(default='', verbose_name='ウェブサイトURL')),
                ('phone', models.CharField(default='', max_length=256, verbose_name='電話番号')),
                ('email', models.EmailField(default='', max_length=256, verbose_name='メールアドレス')),
                ('commnet', models.TextField(default='', max_length=500, verbose_name='お店からのコメント')),
                ('benefits', models.TextField(default='', max_length=500, verbose_name='寄付の特典')),
                ('phot', models.ImageField(default=None, upload_to='media', verbose_name='お店の写真')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.BankAccount', verbose_name='銀行口座')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ZipCode', verbose_name='郵便番号')),
            ],
            options={
                'verbose_name_plural': '店舗情報',
                'db_table': 'restaurant_restaurant',
            },
        ),
    ]
