# Generated by Django 3.0.5 on 2020-04-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='commnet',
            new_name='comment',
        ),
    ]
