# Generated by Django 3.0.5 on 2020-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phot',
            field=models.ImageField(default=None, upload_to='media', verbose_name='お店の写真'),
        ),
    ]
