# Generated by Django 3.0.5 on 2020-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': '口座情報'},
        ),
        migrations.AlterModelOptions(
            name='municipalities',
            options={'verbose_name': '市区町村'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'verbose_name': '都道府県'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name': '店舗情報'},
        ),
        migrations.AlterModelOptions(
            name='streetname',
            options={'verbose_name': '町名'},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name': '郵便番号'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='', max_length=256, verbose_name='口座人名義'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_num',
            field=models.CharField(default='', max_length=256, verbose_name='口座番号'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(default='', max_length=256, verbose_name='口座種別'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='', max_length=256, verbose_name='銀行名'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch',
            field=models.CharField(default='', max_length=256, verbose_name='支店名'),
        ),
        migrations.AlterField(
            model_name='municipalities',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='benefits',
            field=models.TextField(default='', max_length=500, verbose_name='寄付の特典'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='bldg',
            field=models.CharField(default='', max_length=256, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='commnet',
            field=models.TextField(default='', max_length=500, verbose_name='お店からのコメント'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(default='', max_length=256, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='name',
            field=models.CharField(max_length=256, verbose_name='レストラン名'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='phone',
            field=models.CharField(default='', max_length=256, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='street_name',
            field=models.CharField(default='', max_length=256, verbose_name='町名'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='street_num',
            field=models.CharField(default='', max_length=256, verbose_name='番地'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='web_url',
            field=models.URLField(default='', verbose_name='ウェブサイトURL'),
        ),
        migrations.AlterField(
            model_name='streetname',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='町名'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(default='', max_length=256, verbose_name='郵便番号'),
        ),
    ]
