# Generated by Django 3.0.5 on 2020-04-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200409_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name_plural': '口座情報'},
        ),
        migrations.AlterModelOptions(
            name='municipalities',
            options={'verbose_name_plural': '市区町村'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'verbose_name_plural': '都道府県'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name_plural': '店舗情報'},
        ),
        migrations.AlterModelOptions(
            name='streetname',
            options={'verbose_name_plural': '町名'},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name_plural': '郵便番号'},
        ),
    ]
