# Generated by Django 3.0.5 on 2020-04-13 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_auto_20200412_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_name',
            field=models.CharField(default='', max_length=256, verbose_name='口座人名義<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_num',
            field=models.CharField(default='', max_length=256, verbose_name='口座番号<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_type',
            field=models.CharField(default='', max_length=256, verbose_name='口座種別<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Address', verbose_name='住所(町名まで)<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='bank_name',
            field=models.CharField(default='', max_length=256, verbose_name='銀行名<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='branch',
            field=models.CharField(default='', max_length=256, verbose_name='支店名<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.TextField(default='', max_length=500, verbose_name='お店からのコメント<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='', max_length=256, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='レストラン名<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.CharField(default='', max_length=100, verbose_name='オーナ名<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='電話番号<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street_num',
            field=models.CharField(default='', max_length=256, verbose_name='番地<必須>'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー名<必須>)'),
        ),
    ]
