# Generated by Django 3.0.5 on 2020-04-13 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200413_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='limit',
            field=models.DateField(default=datetime.datetime.now, verbose_name='支援期限<必須>'),
        ),
    ]
