# Generated by Django 3.0.5 on 2020-04-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200409_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ZipCode', verbose_name='郵便番号'),
        ),
    ]
