# Generated by Django 3.0.5 on 2020-04-13 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='limit',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='支援期限<必須>'),
        ),
    ]
