# Generated by Django 3.0.5 on 2020-04-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20200409_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurante',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurante_id',
            new_name='restaurant_id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ZipCode', verbose_name='郵便番号'),
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant_restaurant',
        ),
    ]
