# Generated by Django 3.0.5 on 2020-04-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200409_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.CharField(default='', max_length=256, verbose_name='オーナ名'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ZipCode', verbose_name='郵便番号'),
        ),
    ]
