# Generated by Django 3.0.5 on 2020-04-13 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200413_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='limit',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='limit_to',
            field=models.DateField(default=datetime.datetime.now, verbose_name='支援期限<必須>'),
        ),
    ]
