# Generated by Django 3.0.5 on 2020-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20200413_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='お店の名前<必須>'),
        ),
    ]
