# Generated by Django 3.0.5 on 2020-04-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20200414_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=256, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='', max_length=256, verbose_name='電話番号<必須>'),
        ),
    ]
